<a href="https://colab.research.google.com/github/fardil-b/DL-PyTorch/blob/main/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [1]:
import torch

## zeros()

Returns a tensor filled with the scalar value `0`, with the shape defined
by the variable argument :attr:`size`.

In [3]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [4]:
w.size()

torch.Size([4, 3])

In [6]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In neural network when we define the weight, we normally start with random numbers, from standard normal distribution --> mean of zero and std deviation of 1

In [8]:
w = torch.randn(4,3)
w

tensor([[ 1.0386,  1.3369,  1.4419],
        [ 0.6198, -1.4313,  0.0167],
        [-0.9168,  0.8383, -0.0720],
        [-0.5230,  0.2255, -0.1605]])

Returns a tensor filled with random numbers from a normal distribution
with mean `0` and variance `1` (also called the standard normal
distribution).

In [10]:
t = torch.randn_like(w)
t

tensor([[-1.0020, -2.1988, -0.7341],
        [-0.8236, -0.5636,  0.2728],
        [ 0.3694, -0.1745,  0.6602],
        [ 0.2819,  0.5986, -0.1155]])

Returns a tensor with the same size as :attr:`input` that is filled with
random numbers from a normal distribution with mean 0 and variance 1.
``torch.randn_like(input)`` is equivalent to
``torch.randn(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.


## fill_()

In pyTorch, any operation that mutates a tensor in-place has an underscore after the function name

In [11]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Fills :attr:`self` tensor with the specified value.


## view()

In [12]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Returns a new tensor with the same data as the :attr:`self` tensor but of a
different :attr:`shape`.

The returned tensor shares the same data and must have the same number
of elements, but may have a different size. For a tensor to be viewed, the new
view size must be compatible with its original size and stride, i.e., each new
view dimension must either be a subspace of an original dimension, or only span
across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
contiguity-like condition that :math:`\forall i = d, \dots, d+k-1`,


In [14]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

convert tensor to a numpy array
--> if the torch tensor is in the cpu, the torch tensor and the numpy array will share their underlying memory location --> so changing one will change the other

In [15]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Returns :attr:`self` tensor as a NumPy :class:`ndarray`. This tensor and the
returned :class:`ndarray` share the same underlying storage. Changes to
:attr:`self` tensor will be reflected in the :class:`ndarray` and vice versa.

In [16]:
type(w.numpy())

numpy.ndarray